apiVersion: apps/v1 
kind: Deployment
metadata:
  name: kubernetes-wisecow-app
  labels: 
     app: wisecow-app

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wisecow-app

  template:
    metadata:
      labels:
        app: wisecow-app
    spec:
      containers:
      - name: wisecow-app
        image: wisecow-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4499
