apiVersion: v1
kind: Service
metadata:
  name: kubernetes-wisecow-app
  labels:
    app: wisecow-app 
spec:
  selector:
    app: wisecow-app 

  ports:
    - port: 4499
      targetPort: 4499

  type: LoadBalancer
