name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: | 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '  
          sudo -i 
          apt update &&
          apt install fortune-mod cowsay -y &&
          chmod 777 /opt/ &&
          mkdir /opt/app &&
          git clone https://github.com/khandelwal-khushik/wisecow-app.git /opt/app &&    
          cd wisecow-app &&
          sh wisecow.sh
          '
            
     

